'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type BsAttachmentCustomEvent, type BsChatbotFeedbackCustomEvent, type BsChatbotHeaderCustomEvent, type BsChatbotResponseActionCustomEvent, type BsChatbotSourcesDrawerCustomEvent, type BsChatbotSuggestionButtonCustomEvent, type BsCheckboxCustomEvent, type BsChipFilterCustomEvent, type BsChipInputCustomEvent, type BsComposerCustomEvent, type BsComposerStatusBannerCustomEvent, type BsDataTableCustomEvent, type BsDialogCustomEvent, type BsInlineTabCustomEvent, type BsInputCustomEvent, type BsMenuItemCustomEvent, type BsNavigationDrawerCustomEvent, type BsNavigationDrawerItemCustomEvent, type BsPaginationCustomEvent, type BsRadioCustomEvent, type BsSliderCustomEvent, type BsSnackbarCustomEvent, type BsSourceLinkCustomEvent, type BsSwitchCustomEvent, type BsTabCustomEvent, type BsToastCustomEvent } from "@brandsync/wc";
import type { Components } from "@brandsync/wc/dist/components";
import { BsAiDisclaimer as BsAiDisclaimerElement, defineCustomElement as defineBsAiDisclaimer } from "@brandsync/wc/dist/components/bs-ai-disclaimer.js";
import { BsAiGreeting as BsAiGreetingElement, defineCustomElement as defineBsAiGreeting } from "@brandsync/wc/dist/components/bs-ai-greeting.js";
import { BsAiThinking as BsAiThinkingElement, defineCustomElement as defineBsAiThinking } from "@brandsync/wc/dist/components/bs-ai-thinking.js";
import { BsAttachmentList as BsAttachmentListElement, defineCustomElement as defineBsAttachmentList } from "@brandsync/wc/dist/components/bs-attachment-list.js";
import { BsAttachment as BsAttachmentElement, defineCustomElement as defineBsAttachment } from "@brandsync/wc/dist/components/bs-attachment.js";
import { BsAvatar as BsAvatarElement, defineCustomElement as defineBsAvatar } from "@brandsync/wc/dist/components/bs-avatar.js";
import { BsBadge as BsBadgeElement, defineCustomElement as defineBsBadge } from "@brandsync/wc/dist/components/bs-badge.js";
import { BsBreadcrumbOverflow as BsBreadcrumbOverflowElement, defineCustomElement as defineBsBreadcrumbOverflow } from "@brandsync/wc/dist/components/bs-breadcrumb-overflow.js";
import { BsBreadcrumb as BsBreadcrumbElement, defineCustomElement as defineBsBreadcrumb } from "@brandsync/wc/dist/components/bs-breadcrumb.js";
import { BsBreadcrumbs as BsBreadcrumbsElement, defineCustomElement as defineBsBreadcrumbs } from "@brandsync/wc/dist/components/bs-breadcrumbs.js";
import { BsButtonSkeleton as BsButtonSkeletonElement, defineCustomElement as defineBsButtonSkeleton } from "@brandsync/wc/dist/components/bs-button-skeleton.js";
import { BsButton as BsButtonElement, defineCustomElement as defineBsButton } from "@brandsync/wc/dist/components/bs-button.js";
import { BsCard as BsCardElement, defineCustomElement as defineBsCard } from "@brandsync/wc/dist/components/bs-card.js";
import { BsChatbotFeedback as BsChatbotFeedbackElement, defineCustomElement as defineBsChatbotFeedback } from "@brandsync/wc/dist/components/bs-chatbot-feedback.js";
import { BsChatbotHeader as BsChatbotHeaderElement, defineCustomElement as defineBsChatbotHeader } from "@brandsync/wc/dist/components/bs-chatbot-header.js";
import { BsChatbotResponseAction as BsChatbotResponseActionElement, defineCustomElement as defineBsChatbotResponseAction } from "@brandsync/wc/dist/components/bs-chatbot-response-action.js";
import { BsChatbotSourcesDrawer as BsChatbotSourcesDrawerElement, defineCustomElement as defineBsChatbotSourcesDrawer } from "@brandsync/wc/dist/components/bs-chatbot-sources-drawer.js";
import { BsChatbotSuggestionButton as BsChatbotSuggestionButtonElement, defineCustomElement as defineBsChatbotSuggestionButton } from "@brandsync/wc/dist/components/bs-chatbot-suggestion-button.js";
import { BsCheckboxSkeleton as BsCheckboxSkeletonElement, defineCustomElement as defineBsCheckboxSkeleton } from "@brandsync/wc/dist/components/bs-checkbox-skeleton.js";
import { BsCheckbox as BsCheckboxElement, defineCustomElement as defineBsCheckbox } from "@brandsync/wc/dist/components/bs-checkbox.js";
import { BsChipFilter as BsChipFilterElement, defineCustomElement as defineBsChipFilter } from "@brandsync/wc/dist/components/bs-chip-filter.js";
import { BsChipInformative as BsChipInformativeElement, defineCustomElement as defineBsChipInformative } from "@brandsync/wc/dist/components/bs-chip-informative.js";
import { BsChipInput as BsChipInputElement, defineCustomElement as defineBsChipInput } from "@brandsync/wc/dist/components/bs-chip-input.js";
import { BsComposerStatusBanner as BsComposerStatusBannerElement, defineCustomElement as defineBsComposerStatusBanner } from "@brandsync/wc/dist/components/bs-composer-status-banner.js";
import { BsComposer as BsComposerElement, defineCustomElement as defineBsComposer } from "@brandsync/wc/dist/components/bs-composer.js";
import { BsDataTable as BsDataTableElement, defineCustomElement as defineBsDataTable } from "@brandsync/wc/dist/components/bs-data-table.js";
import { BsDialog as BsDialogElement, defineCustomElement as defineBsDialog } from "@brandsync/wc/dist/components/bs-dialog.js";
import { BsIconButton as BsIconButtonElement, defineCustomElement as defineBsIconButton } from "@brandsync/wc/dist/components/bs-icon-button.js";
import { BsInlineTab as BsInlineTabElement, defineCustomElement as defineBsInlineTab } from "@brandsync/wc/dist/components/bs-inline-tab.js";
import { BsInput as BsInputElement, defineCustomElement as defineBsInput } from "@brandsync/wc/dist/components/bs-input.js";
import { BsLogo as BsLogoElement, defineCustomElement as defineBsLogo } from "@brandsync/wc/dist/components/bs-logo.js";
import { BsMenuItem as BsMenuItemElement, defineCustomElement as defineBsMenuItem } from "@brandsync/wc/dist/components/bs-menu-item.js";
import { BsMenu as BsMenuElement, defineCustomElement as defineBsMenu } from "@brandsync/wc/dist/components/bs-menu.js";
import { BsNavigationDrawerItem as BsNavigationDrawerItemElement, defineCustomElement as defineBsNavigationDrawerItem } from "@brandsync/wc/dist/components/bs-navigation-drawer-item.js";
import { BsNavigationDrawer as BsNavigationDrawerElement, defineCustomElement as defineBsNavigationDrawer } from "@brandsync/wc/dist/components/bs-navigation-drawer.js";
import { BsNavigationHeader as BsNavigationHeaderElement, defineCustomElement as defineBsNavigationHeader } from "@brandsync/wc/dist/components/bs-navigation-header.js";
import { BsPagination as BsPaginationElement, defineCustomElement as defineBsPagination } from "@brandsync/wc/dist/components/bs-pagination.js";
import { BsRadio as BsRadioElement, defineCustomElement as defineBsRadio } from "@brandsync/wc/dist/components/bs-radio.js";
import { BsSlider as BsSliderElement, defineCustomElement as defineBsSlider } from "@brandsync/wc/dist/components/bs-slider.js";
import { BsSnackbar as BsSnackbarElement, defineCustomElement as defineBsSnackbar } from "@brandsync/wc/dist/components/bs-snackbar.js";
import { BsSourceLink as BsSourceLinkElement, defineCustomElement as defineBsSourceLink } from "@brandsync/wc/dist/components/bs-source-link.js";
import { BsStepperStep as BsStepperStepElement, defineCustomElement as defineBsStepperStep } from "@brandsync/wc/dist/components/bs-stepper-step.js";
import { BsStepper as BsStepperElement, defineCustomElement as defineBsStepper } from "@brandsync/wc/dist/components/bs-stepper.js";
import { BsSwitch as BsSwitchElement, defineCustomElement as defineBsSwitch } from "@brandsync/wc/dist/components/bs-switch.js";
import { BsTab as BsTabElement, defineCustomElement as defineBsTab } from "@brandsync/wc/dist/components/bs-tab.js";
import { BsTabs as BsTabsElement, defineCustomElement as defineBsTabs } from "@brandsync/wc/dist/components/bs-tabs.js";
import { BsToast as BsToastElement, defineCustomElement as defineBsToast } from "@brandsync/wc/dist/components/bs-toast.js";
import { BsTooltip as BsTooltipElement, defineCustomElement as defineBsTooltip } from "@brandsync/wc/dist/components/bs-tooltip.js";

export type BsAiDisclaimerEvents = NonNullable<unknown>;

export const BsAiDisclaimer: StencilReactComponent<BsAiDisclaimerElement, BsAiDisclaimerEvents, Components.BsAiDisclaimer> = /*@__PURE__*/ createComponent<BsAiDisclaimerElement, BsAiDisclaimerEvents, Components.BsAiDisclaimer>({
    tagName: 'bs-ai-disclaimer',
    elementClass: BsAiDisclaimerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsAiDisclaimerEvents,
    defineCustomElement: defineBsAiDisclaimer
});

export type BsAiGreetingEvents = NonNullable<unknown>;

export const BsAiGreeting: StencilReactComponent<BsAiGreetingElement, BsAiGreetingEvents, Components.BsAiGreeting> = /*@__PURE__*/ createComponent<BsAiGreetingElement, BsAiGreetingEvents, Components.BsAiGreeting>({
    tagName: 'bs-ai-greeting',
    elementClass: BsAiGreetingElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsAiGreetingEvents,
    defineCustomElement: defineBsAiGreeting
});

export type BsAiThinkingEvents = NonNullable<unknown>;

export const BsAiThinking: StencilReactComponent<BsAiThinkingElement, BsAiThinkingEvents, Components.BsAiThinking> = /*@__PURE__*/ createComponent<BsAiThinkingElement, BsAiThinkingEvents, Components.BsAiThinking>({
    tagName: 'bs-ai-thinking',
    elementClass: BsAiThinkingElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsAiThinkingEvents,
    defineCustomElement: defineBsAiThinking
});

export type BsAttachmentEvents = { onBsRemove: EventName<BsAttachmentCustomEvent<void>> };

export const BsAttachment: StencilReactComponent<BsAttachmentElement, BsAttachmentEvents, Components.BsAttachment> = /*@__PURE__*/ createComponent<BsAttachmentElement, BsAttachmentEvents, Components.BsAttachment>({
    tagName: 'bs-attachment',
    elementClass: BsAttachmentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsRemove: 'bsRemove' } as BsAttachmentEvents,
    defineCustomElement: defineBsAttachment
});

export type BsAttachmentListEvents = NonNullable<unknown>;

export const BsAttachmentList: StencilReactComponent<BsAttachmentListElement, BsAttachmentListEvents, Components.BsAttachmentList> = /*@__PURE__*/ createComponent<BsAttachmentListElement, BsAttachmentListEvents, Components.BsAttachmentList>({
    tagName: 'bs-attachment-list',
    elementClass: BsAttachmentListElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsAttachmentListEvents,
    defineCustomElement: defineBsAttachmentList
});

export type BsAvatarEvents = NonNullable<unknown>;

export const BsAvatar: StencilReactComponent<BsAvatarElement, BsAvatarEvents, Components.BsAvatar> = /*@__PURE__*/ createComponent<BsAvatarElement, BsAvatarEvents, Components.BsAvatar>({
    tagName: 'bs-avatar',
    elementClass: BsAvatarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsAvatarEvents,
    defineCustomElement: defineBsAvatar
});

export type BsBadgeEvents = NonNullable<unknown>;

export const BsBadge: StencilReactComponent<BsBadgeElement, BsBadgeEvents, Components.BsBadge> = /*@__PURE__*/ createComponent<BsBadgeElement, BsBadgeEvents, Components.BsBadge>({
    tagName: 'bs-badge',
    elementClass: BsBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsBadgeEvents,
    defineCustomElement: defineBsBadge
});

export type BsBreadcrumbEvents = NonNullable<unknown>;

export const BsBreadcrumb: StencilReactComponent<BsBreadcrumbElement, BsBreadcrumbEvents, Components.BsBreadcrumb> = /*@__PURE__*/ createComponent<BsBreadcrumbElement, BsBreadcrumbEvents, Components.BsBreadcrumb>({
    tagName: 'bs-breadcrumb',
    elementClass: BsBreadcrumbElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsBreadcrumbEvents,
    defineCustomElement: defineBsBreadcrumb
});

export type BsBreadcrumbOverflowEvents = NonNullable<unknown>;

export const BsBreadcrumbOverflow: StencilReactComponent<BsBreadcrumbOverflowElement, BsBreadcrumbOverflowEvents, Components.BsBreadcrumbOverflow> = /*@__PURE__*/ createComponent<BsBreadcrumbOverflowElement, BsBreadcrumbOverflowEvents, Components.BsBreadcrumbOverflow>({
    tagName: 'bs-breadcrumb-overflow',
    elementClass: BsBreadcrumbOverflowElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsBreadcrumbOverflowEvents,
    defineCustomElement: defineBsBreadcrumbOverflow
});

export type BsBreadcrumbsEvents = NonNullable<unknown>;

export const BsBreadcrumbs: StencilReactComponent<BsBreadcrumbsElement, BsBreadcrumbsEvents, Components.BsBreadcrumbs> = /*@__PURE__*/ createComponent<BsBreadcrumbsElement, BsBreadcrumbsEvents, Components.BsBreadcrumbs>({
    tagName: 'bs-breadcrumbs',
    elementClass: BsBreadcrumbsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsBreadcrumbsEvents,
    defineCustomElement: defineBsBreadcrumbs
});

export type BsButtonEvents = NonNullable<unknown>;

export const BsButton: StencilReactComponent<BsButtonElement, BsButtonEvents, Components.BsButton> = /*@__PURE__*/ createComponent<BsButtonElement, BsButtonEvents, Components.BsButton>({
    tagName: 'bs-button',
    elementClass: BsButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsButtonEvents,
    defineCustomElement: defineBsButton
});

export type BsButtonSkeletonEvents = NonNullable<unknown>;

export const BsButtonSkeleton: StencilReactComponent<BsButtonSkeletonElement, BsButtonSkeletonEvents, Components.BsButtonSkeleton> = /*@__PURE__*/ createComponent<BsButtonSkeletonElement, BsButtonSkeletonEvents, Components.BsButtonSkeleton>({
    tagName: 'bs-button-skeleton',
    elementClass: BsButtonSkeletonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsButtonSkeletonEvents,
    defineCustomElement: defineBsButtonSkeleton
});

export type BsCardEvents = NonNullable<unknown>;

export const BsCard: StencilReactComponent<BsCardElement, BsCardEvents, Components.BsCard> = /*@__PURE__*/ createComponent<BsCardElement, BsCardEvents, Components.BsCard>({
    tagName: 'bs-card',
    elementClass: BsCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsCardEvents,
    defineCustomElement: defineBsCard
});

export type BsChatbotFeedbackEvents = {
    onBsRatingChange: EventName<BsChatbotFeedbackCustomEvent<number>>,
    onBsCommentInput: EventName<BsChatbotFeedbackCustomEvent<string>>,
    onBsSubmit: EventName<BsChatbotFeedbackCustomEvent<{ rating: number; comment: string }>>,
    onBsNewChat: EventName<BsChatbotFeedbackCustomEvent<void>>,
    onBsClose: EventName<BsChatbotFeedbackCustomEvent<void>>
};

export const BsChatbotFeedback: StencilReactComponent<BsChatbotFeedbackElement, BsChatbotFeedbackEvents, Components.BsChatbotFeedback> = /*@__PURE__*/ createComponent<BsChatbotFeedbackElement, BsChatbotFeedbackEvents, Components.BsChatbotFeedback>({
    tagName: 'bs-chatbot-feedback',
    elementClass: BsChatbotFeedbackElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBsRatingChange: 'bsRatingChange',
        onBsCommentInput: 'bsCommentInput',
        onBsSubmit: 'bsSubmit',
        onBsNewChat: 'bsNewChat',
        onBsClose: 'bsClose'
    } as BsChatbotFeedbackEvents,
    defineCustomElement: defineBsChatbotFeedback
});

export type BsChatbotHeaderEvents = {
    onBsNewChat: EventName<BsChatbotHeaderCustomEvent<void>>,
    onBsHistory: EventName<BsChatbotHeaderCustomEvent<void>>,
    onBsExpand: EventName<BsChatbotHeaderCustomEvent<boolean>>,
    onBsClose: EventName<BsChatbotHeaderCustomEvent<void>>
};

export const BsChatbotHeader: StencilReactComponent<BsChatbotHeaderElement, BsChatbotHeaderEvents, Components.BsChatbotHeader> = /*@__PURE__*/ createComponent<BsChatbotHeaderElement, BsChatbotHeaderEvents, Components.BsChatbotHeader>({
    tagName: 'bs-chatbot-header',
    elementClass: BsChatbotHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBsNewChat: 'bsNewChat',
        onBsHistory: 'bsHistory',
        onBsExpand: 'bsExpand',
        onBsClose: 'bsClose'
    } as BsChatbotHeaderEvents,
    defineCustomElement: defineBsChatbotHeader
});

export type BsChatbotResponseActionEvents = {
    onBsLike: EventName<BsChatbotResponseActionCustomEvent<void>>,
    onBsDislike: EventName<BsChatbotResponseActionCustomEvent<void>>,
    onBsCopy: EventName<BsChatbotResponseActionCustomEvent<void>>,
    onBsRegenerate: EventName<BsChatbotResponseActionCustomEvent<void>>,
    onBsMenuOpen: EventName<BsChatbotResponseActionCustomEvent<boolean>>,
    onBsSourcesClick: EventName<BsChatbotResponseActionCustomEvent<void>>
};

export const BsChatbotResponseAction: StencilReactComponent<BsChatbotResponseActionElement, BsChatbotResponseActionEvents, Components.BsChatbotResponseAction> = /*@__PURE__*/ createComponent<BsChatbotResponseActionElement, BsChatbotResponseActionEvents, Components.BsChatbotResponseAction>({
    tagName: 'bs-chatbot-response-action',
    elementClass: BsChatbotResponseActionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBsLike: 'bsLike',
        onBsDislike: 'bsDislike',
        onBsCopy: 'bsCopy',
        onBsRegenerate: 'bsRegenerate',
        onBsMenuOpen: 'bsMenuOpen',
        onBsSourcesClick: 'bsSourcesClick'
    } as BsChatbotResponseActionEvents,
    defineCustomElement: defineBsChatbotResponseAction
});

export type BsChatbotSourcesDrawerEvents = { onBsCollapse: EventName<BsChatbotSourcesDrawerCustomEvent<void>> };

export const BsChatbotSourcesDrawer: StencilReactComponent<BsChatbotSourcesDrawerElement, BsChatbotSourcesDrawerEvents, Components.BsChatbotSourcesDrawer> = /*@__PURE__*/ createComponent<BsChatbotSourcesDrawerElement, BsChatbotSourcesDrawerEvents, Components.BsChatbotSourcesDrawer>({
    tagName: 'bs-chatbot-sources-drawer',
    elementClass: BsChatbotSourcesDrawerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsCollapse: 'bsCollapse' } as BsChatbotSourcesDrawerEvents,
    defineCustomElement: defineBsChatbotSourcesDrawer
});

export type BsChatbotSuggestionButtonEvents = { onBsSelect: EventName<BsChatbotSuggestionButtonCustomEvent<void>> };

export const BsChatbotSuggestionButton: StencilReactComponent<BsChatbotSuggestionButtonElement, BsChatbotSuggestionButtonEvents, Components.BsChatbotSuggestionButton> = /*@__PURE__*/ createComponent<BsChatbotSuggestionButtonElement, BsChatbotSuggestionButtonEvents, Components.BsChatbotSuggestionButton>({
    tagName: 'bs-chatbot-suggestion-button',
    elementClass: BsChatbotSuggestionButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsSelect: 'bsSelect' } as BsChatbotSuggestionButtonEvents,
    defineCustomElement: defineBsChatbotSuggestionButton
});

export type BsCheckboxEvents = { onBsChange: EventName<BsCheckboxCustomEvent<boolean>> };

export const BsCheckbox: StencilReactComponent<BsCheckboxElement, BsCheckboxEvents, Components.BsCheckbox> = /*@__PURE__*/ createComponent<BsCheckboxElement, BsCheckboxEvents, Components.BsCheckbox>({
    tagName: 'bs-checkbox',
    elementClass: BsCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsChange: 'bsChange' } as BsCheckboxEvents,
    defineCustomElement: defineBsCheckbox
});

export type BsCheckboxSkeletonEvents = NonNullable<unknown>;

export const BsCheckboxSkeleton: StencilReactComponent<BsCheckboxSkeletonElement, BsCheckboxSkeletonEvents, Components.BsCheckboxSkeleton> = /*@__PURE__*/ createComponent<BsCheckboxSkeletonElement, BsCheckboxSkeletonEvents, Components.BsCheckboxSkeleton>({
    tagName: 'bs-checkbox-skeleton',
    elementClass: BsCheckboxSkeletonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsCheckboxSkeletonEvents,
    defineCustomElement: defineBsCheckboxSkeleton
});

export type BsChipFilterEvents = { onBsChange: EventName<BsChipFilterCustomEvent<boolean>> };

export const BsChipFilter: StencilReactComponent<BsChipFilterElement, BsChipFilterEvents, Components.BsChipFilter> = /*@__PURE__*/ createComponent<BsChipFilterElement, BsChipFilterEvents, Components.BsChipFilter>({
    tagName: 'bs-chip-filter',
    elementClass: BsChipFilterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsChange: 'bsChange' } as BsChipFilterEvents,
    defineCustomElement: defineBsChipFilter
});

export type BsChipInformativeEvents = NonNullable<unknown>;

export const BsChipInformative: StencilReactComponent<BsChipInformativeElement, BsChipInformativeEvents, Components.BsChipInformative> = /*@__PURE__*/ createComponent<BsChipInformativeElement, BsChipInformativeEvents, Components.BsChipInformative>({
    tagName: 'bs-chip-informative',
    elementClass: BsChipInformativeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsChipInformativeEvents,
    defineCustomElement: defineBsChipInformative
});

export type BsChipInputEvents = {
    onBsChange: EventName<BsChipInputCustomEvent<boolean>>,
    onBsRemove: EventName<BsChipInputCustomEvent<void>>
};

export const BsChipInput: StencilReactComponent<BsChipInputElement, BsChipInputEvents, Components.BsChipInput> = /*@__PURE__*/ createComponent<BsChipInputElement, BsChipInputEvents, Components.BsChipInput>({
    tagName: 'bs-chip-input',
    elementClass: BsChipInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBsChange: 'bsChange',
        onBsRemove: 'bsRemove'
    } as BsChipInputEvents,
    defineCustomElement: defineBsChipInput
});

export type BsComposerEvents = {
    onBsInput: EventName<BsComposerCustomEvent<string>>,
    onBsSubmit: EventName<BsComposerCustomEvent<void>>,
    onBsStop: EventName<BsComposerCustomEvent<void>>,
    onBsVoiceConfirm: EventName<BsComposerCustomEvent<void>>,
    onBsAttach: EventName<BsComposerCustomEvent<void>>,
    onBsMicToggle: EventName<BsComposerCustomEvent<void>>
};

export const BsComposer: StencilReactComponent<BsComposerElement, BsComposerEvents, Components.BsComposer> = /*@__PURE__*/ createComponent<BsComposerElement, BsComposerEvents, Components.BsComposer>({
    tagName: 'bs-composer',
    elementClass: BsComposerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBsInput: 'bsInput',
        onBsSubmit: 'bsSubmit',
        onBsStop: 'bsStop',
        onBsVoiceConfirm: 'bsVoiceConfirm',
        onBsAttach: 'bsAttach',
        onBsMicToggle: 'bsMicToggle'
    } as BsComposerEvents,
    defineCustomElement: defineBsComposer
});

export type BsComposerStatusBannerEvents = {
    onBsAction: EventName<BsComposerStatusBannerCustomEvent<void>>,
    onBsClose: EventName<BsComposerStatusBannerCustomEvent<void>>
};

export const BsComposerStatusBanner: StencilReactComponent<BsComposerStatusBannerElement, BsComposerStatusBannerEvents, Components.BsComposerStatusBanner> = /*@__PURE__*/ createComponent<BsComposerStatusBannerElement, BsComposerStatusBannerEvents, Components.BsComposerStatusBanner>({
    tagName: 'bs-composer-status-banner',
    elementClass: BsComposerStatusBannerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBsAction: 'bsAction',
        onBsClose: 'bsClose'
    } as BsComposerStatusBannerEvents,
    defineCustomElement: defineBsComposerStatusBanner
});

export type BsDataTableEvents = {
    onBsSort: EventName<BsDataTableCustomEvent<{ column: string; direction: 'asc' | 'desc' }>>,
    onBsRowSelect: EventName<BsDataTableCustomEvent<{ id: string | number; selected: boolean }>>
};

export const BsDataTable: StencilReactComponent<BsDataTableElement, BsDataTableEvents, Components.BsDataTable> = /*@__PURE__*/ createComponent<BsDataTableElement, BsDataTableEvents, Components.BsDataTable>({
    tagName: 'bs-data-table',
    elementClass: BsDataTableElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBsSort: 'bsSort',
        onBsRowSelect: 'bsRowSelect'
    } as BsDataTableEvents,
    defineCustomElement: defineBsDataTable
});

export type BsDialogEvents = { onBsClose: EventName<BsDialogCustomEvent<void>> };

export const BsDialog: StencilReactComponent<BsDialogElement, BsDialogEvents, Components.BsDialog> = /*@__PURE__*/ createComponent<BsDialogElement, BsDialogEvents, Components.BsDialog>({
    tagName: 'bs-dialog',
    elementClass: BsDialogElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsClose: 'bsClose' } as BsDialogEvents,
    defineCustomElement: defineBsDialog
});

export type BsIconButtonEvents = NonNullable<unknown>;

export const BsIconButton: StencilReactComponent<BsIconButtonElement, BsIconButtonEvents, Components.BsIconButton> = /*@__PURE__*/ createComponent<BsIconButtonElement, BsIconButtonEvents, Components.BsIconButton>({
    tagName: 'bs-icon-button',
    elementClass: BsIconButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsIconButtonEvents,
    defineCustomElement: defineBsIconButton
});

export type BsInlineTabEvents = { onBsSelect: EventName<BsInlineTabCustomEvent<void>> };

export const BsInlineTab: StencilReactComponent<BsInlineTabElement, BsInlineTabEvents, Components.BsInlineTab> = /*@__PURE__*/ createComponent<BsInlineTabElement, BsInlineTabEvents, Components.BsInlineTab>({
    tagName: 'bs-inline-tab',
    elementClass: BsInlineTabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsSelect: 'bsSelect' } as BsInlineTabEvents,
    defineCustomElement: defineBsInlineTab
});

export type BsInputEvents = {
    onBsInput: EventName<BsInputCustomEvent<string>>,
    onBsChange: EventName<BsInputCustomEvent<string>>,
    onBsOpen: EventName<BsInputCustomEvent<boolean>>,
    onBsChipAdd: EventName<BsInputCustomEvent<string>>,
    onBsChipRemove: EventName<BsInputCustomEvent<string>>,
    onBsTitleChange: EventName<BsInputCustomEvent<string>>,
    onBsCountryChange: EventName<BsInputCustomEvent<string>>
};

export const BsInput: StencilReactComponent<BsInputElement, BsInputEvents, Components.BsInput> = /*@__PURE__*/ createComponent<BsInputElement, BsInputEvents, Components.BsInput>({
    tagName: 'bs-input',
    elementClass: BsInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBsInput: 'bsInput',
        onBsChange: 'bsChange',
        onBsOpen: 'bsOpen',
        onBsChipAdd: 'bsChipAdd',
        onBsChipRemove: 'bsChipRemove',
        onBsTitleChange: 'bsTitleChange',
        onBsCountryChange: 'bsCountryChange'
    } as BsInputEvents,
    defineCustomElement: defineBsInput
});

export type BsLogoEvents = NonNullable<unknown>;

export const BsLogo: StencilReactComponent<BsLogoElement, BsLogoEvents, Components.BsLogo> = /*@__PURE__*/ createComponent<BsLogoElement, BsLogoEvents, Components.BsLogo>({
    tagName: 'bs-logo',
    elementClass: BsLogoElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsLogoEvents,
    defineCustomElement: defineBsLogo
});

export type BsMenuEvents = NonNullable<unknown>;

export const BsMenu: StencilReactComponent<BsMenuElement, BsMenuEvents, Components.BsMenu> = /*@__PURE__*/ createComponent<BsMenuElement, BsMenuEvents, Components.BsMenu>({
    tagName: 'bs-menu',
    elementClass: BsMenuElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsMenuEvents,
    defineCustomElement: defineBsMenu
});

export type BsMenuItemEvents = { onBsSelect: EventName<BsMenuItemCustomEvent<void>> };

export const BsMenuItem: StencilReactComponent<BsMenuItemElement, BsMenuItemEvents, Components.BsMenuItem> = /*@__PURE__*/ createComponent<BsMenuItemElement, BsMenuItemEvents, Components.BsMenuItem>({
    tagName: 'bs-menu-item',
    elementClass: BsMenuItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsSelect: 'bsSelect' } as BsMenuItemEvents,
    defineCustomElement: defineBsMenuItem
});

export type BsNavigationDrawerEvents = {
    onBsCollapse: EventName<BsNavigationDrawerCustomEvent<boolean>>,
    onBsSearchClick: EventName<BsNavigationDrawerCustomEvent<void>>
};

export const BsNavigationDrawer: StencilReactComponent<BsNavigationDrawerElement, BsNavigationDrawerEvents, Components.BsNavigationDrawer> = /*@__PURE__*/ createComponent<BsNavigationDrawerElement, BsNavigationDrawerEvents, Components.BsNavigationDrawer>({
    tagName: 'bs-navigation-drawer',
    elementClass: BsNavigationDrawerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBsCollapse: 'bsCollapse',
        onBsSearchClick: 'bsSearchClick'
    } as BsNavigationDrawerEvents,
    defineCustomElement: defineBsNavigationDrawer
});

export type BsNavigationDrawerItemEvents = {
    onBsSelect: EventName<BsNavigationDrawerItemCustomEvent<void>>,
    onBsToggle: EventName<BsNavigationDrawerItemCustomEvent<boolean>>
};

export const BsNavigationDrawerItem: StencilReactComponent<BsNavigationDrawerItemElement, BsNavigationDrawerItemEvents, Components.BsNavigationDrawerItem> = /*@__PURE__*/ createComponent<BsNavigationDrawerItemElement, BsNavigationDrawerItemEvents, Components.BsNavigationDrawerItem>({
    tagName: 'bs-navigation-drawer-item',
    elementClass: BsNavigationDrawerItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBsSelect: 'bsSelect',
        onBsToggle: 'bsToggle'
    } as BsNavigationDrawerItemEvents,
    defineCustomElement: defineBsNavigationDrawerItem
});

export type BsNavigationHeaderEvents = NonNullable<unknown>;

export const BsNavigationHeader: StencilReactComponent<BsNavigationHeaderElement, BsNavigationHeaderEvents, Components.BsNavigationHeader> = /*@__PURE__*/ createComponent<BsNavigationHeaderElement, BsNavigationHeaderEvents, Components.BsNavigationHeader>({
    tagName: 'bs-navigation-header',
    elementClass: BsNavigationHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsNavigationHeaderEvents,
    defineCustomElement: defineBsNavigationHeader
});

export type BsPaginationEvents = { onBsPageChange: EventName<BsPaginationCustomEvent<number>> };

export const BsPagination: StencilReactComponent<BsPaginationElement, BsPaginationEvents, Components.BsPagination> = /*@__PURE__*/ createComponent<BsPaginationElement, BsPaginationEvents, Components.BsPagination>({
    tagName: 'bs-pagination',
    elementClass: BsPaginationElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsPageChange: 'bsPageChange' } as BsPaginationEvents,
    defineCustomElement: defineBsPagination
});

export type BsRadioEvents = { onBsChange: EventName<BsRadioCustomEvent<string>> };

export const BsRadio: StencilReactComponent<BsRadioElement, BsRadioEvents, Components.BsRadio> = /*@__PURE__*/ createComponent<BsRadioElement, BsRadioEvents, Components.BsRadio>({
    tagName: 'bs-radio',
    elementClass: BsRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsChange: 'bsChange' } as BsRadioEvents,
    defineCustomElement: defineBsRadio
});

export type BsSliderEvents = {
    onBsChange: EventName<BsSliderCustomEvent<number>>,
    onBsRangeChange: EventName<BsSliderCustomEvent<{ start: number; end: number }>>
};

export const BsSlider: StencilReactComponent<BsSliderElement, BsSliderEvents, Components.BsSlider> = /*@__PURE__*/ createComponent<BsSliderElement, BsSliderEvents, Components.BsSlider>({
    tagName: 'bs-slider',
    elementClass: BsSliderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBsChange: 'bsChange',
        onBsRangeChange: 'bsRangeChange'
    } as BsSliderEvents,
    defineCustomElement: defineBsSlider
});

export type BsSnackbarEvents = {
    onBsAction: EventName<BsSnackbarCustomEvent<void>>,
    onBsDismiss: EventName<BsSnackbarCustomEvent<void>>
};

export const BsSnackbar: StencilReactComponent<BsSnackbarElement, BsSnackbarEvents, Components.BsSnackbar> = /*@__PURE__*/ createComponent<BsSnackbarElement, BsSnackbarEvents, Components.BsSnackbar>({
    tagName: 'bs-snackbar',
    elementClass: BsSnackbarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBsAction: 'bsAction',
        onBsDismiss: 'bsDismiss'
    } as BsSnackbarEvents,
    defineCustomElement: defineBsSnackbar
});

export type BsSourceLinkEvents = { onBsOpen: EventName<BsSourceLinkCustomEvent<void>> };

export const BsSourceLink: StencilReactComponent<BsSourceLinkElement, BsSourceLinkEvents, Components.BsSourceLink> = /*@__PURE__*/ createComponent<BsSourceLinkElement, BsSourceLinkEvents, Components.BsSourceLink>({
    tagName: 'bs-source-link',
    elementClass: BsSourceLinkElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsOpen: 'bsOpen' } as BsSourceLinkEvents,
    defineCustomElement: defineBsSourceLink
});

export type BsStepperEvents = NonNullable<unknown>;

export const BsStepper: StencilReactComponent<BsStepperElement, BsStepperEvents, Components.BsStepper> = /*@__PURE__*/ createComponent<BsStepperElement, BsStepperEvents, Components.BsStepper>({
    tagName: 'bs-stepper',
    elementClass: BsStepperElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsStepperEvents,
    defineCustomElement: defineBsStepper
});

export type BsStepperStepEvents = NonNullable<unknown>;

export const BsStepperStep: StencilReactComponent<BsStepperStepElement, BsStepperStepEvents, Components.BsStepperStep> = /*@__PURE__*/ createComponent<BsStepperStepElement, BsStepperStepEvents, Components.BsStepperStep>({
    tagName: 'bs-stepper-step',
    elementClass: BsStepperStepElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsStepperStepEvents,
    defineCustomElement: defineBsStepperStep
});

export type BsSwitchEvents = { onBsChange: EventName<BsSwitchCustomEvent<boolean>> };

export const BsSwitch: StencilReactComponent<BsSwitchElement, BsSwitchEvents, Components.BsSwitch> = /*@__PURE__*/ createComponent<BsSwitchElement, BsSwitchEvents, Components.BsSwitch>({
    tagName: 'bs-switch',
    elementClass: BsSwitchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsChange: 'bsChange' } as BsSwitchEvents,
    defineCustomElement: defineBsSwitch
});

export type BsTabEvents = { onBsSelect: EventName<BsTabCustomEvent<void>> };

export const BsTab: StencilReactComponent<BsTabElement, BsTabEvents, Components.BsTab> = /*@__PURE__*/ createComponent<BsTabElement, BsTabEvents, Components.BsTab>({
    tagName: 'bs-tab',
    elementClass: BsTabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsSelect: 'bsSelect' } as BsTabEvents,
    defineCustomElement: defineBsTab
});

export type BsTabsEvents = NonNullable<unknown>;

export const BsTabs: StencilReactComponent<BsTabsElement, BsTabsEvents, Components.BsTabs> = /*@__PURE__*/ createComponent<BsTabsElement, BsTabsEvents, Components.BsTabs>({
    tagName: 'bs-tabs',
    elementClass: BsTabsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsTabsEvents,
    defineCustomElement: defineBsTabs
});

export type BsToastEvents = { onBsDismiss: EventName<BsToastCustomEvent<void>> };

export const BsToast: StencilReactComponent<BsToastElement, BsToastEvents, Components.BsToast> = /*@__PURE__*/ createComponent<BsToastElement, BsToastEvents, Components.BsToast>({
    tagName: 'bs-toast',
    elementClass: BsToastElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBsDismiss: 'bsDismiss' } as BsToastEvents,
    defineCustomElement: defineBsToast
});

export type BsTooltipEvents = NonNullable<unknown>;

export const BsTooltip: StencilReactComponent<BsTooltipElement, BsTooltipEvents, Components.BsTooltip> = /*@__PURE__*/ createComponent<BsTooltipElement, BsTooltipEvents, Components.BsTooltip>({
    tagName: 'bs-tooltip',
    elementClass: BsTooltipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as BsTooltipEvents,
    defineCustomElement: defineBsTooltip
});
